# SPDX-FileCopyrightText: 2025-2026 Technology Innovation Institute (TII)
# SPDX-License-Identifier: Apache-2.0
#
# Built from source, not the release tarball: that asset is multiarch and would
# pull a 32-bit glibc and libunwind in for tooling we only run 64-bit.
{
  lib,
  stdenv,
  fetchFromGitHub,
  cmake,
  ninja,
  perl,
  makeWrapper,
  coreutils,
  zlib,
  snappy,
  lz4,
  xxhash,
  libunwind,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "dynamorio";
  # cronbuild-* is cut weekly; the release_* line has not moved since Jan 2025.
  # The third component is a day count, not a patch level.
  version = "11.91.20708";

  src = fetchFromGitHub {
    owner = "DynamoRIO";
    repo = "dynamorio";
    tag = "cronbuild-${finalAttrs.version}";
    # ext/drsyms raises FATAL_ERROR without third_party/elfutils, so the plain
    # source tarball cannot be used.
    fetchSubmodules = true;
    hash = "sha256-zZOyLqzi8VRTGcZrAgIE20ATuIFDYep/3Kkd5THKx7k=";
  };

  strictDeps = true;

  nativeBuildInputs = [
    cmake
    ninja
    # FATAL_ERROR without it: the instruction tables are generated by perl.
    perl
    makeWrapper
  ];

  buildInputs = [
    zlib
    snappy
    lz4
    xxhash
    libunwind
  ];

  cmakeFlags = [
    # Otherwise the patchlevel comes from `date +%s / 86400`.
    (lib.cmakeFeature "VERSION_NUMBER" finalAttrs.version)
    # Defaults ON but degrades silently when doxygen is absent.
    (lib.cmakeBool "BUILD_DOCS" false)
  ];

  # The core runs on private TLS, so an app-TLS stack canary is fatal. Upstream
  # sets -fno-stack-protector itself, but cc-wrapper injects behind CMake's back.
  hardeningDisable = [ "all" ];

  # SPLIT_SYMBOLS already objcopied debug info into lib64/*.debug, which is on
  # the default stripDebugList.
  dontStrip = true;

  postInstall = ''
    # -use_dll silences drdeploy.c's root check, which wants all four of
    # lib{32,64}/{debug,release} and warns about the three we do not build.
    # Narrower than -quiet, whose `nowarn` is global rather than per-check.
    # lib64 is correct both before and after the moveLib64 hook.
    wrapProgram "$out/bin64/drrun" \
      --add-flags "-root $out" \
      --add-flags "-use_dll $out/lib64/release/libdynamorio.so"

    # drconfig rejects -use_dll.
    wrapProgram "$out/bin64/drconfig" --add-flags "-root $out"

    mkdir -p "$out/bin"
    ln -s ../bin64/drrun "$out/bin/drrun"
    ln -s ../bin64/drconfig "$out/bin/drconfig"
  '';

  doInstallCheck = true;

  # -version alone passes even when the code cache cannot start.
  installCheckPhase = ''
    runHook preInstallCheck

    "$out/bin/drrun" -version

    out_and_err=$("$out/bin/drrun" -- "${coreutils}/bin/echo" dynamorio-ok 2>&1)
    case $out_and_err in
      *dynamorio-ok*) ;;
      *) echo "drrun did not run the target:"; echo "$out_and_err"; exit 1 ;;
    esac

    case $out_and_err in
      *WARNING*) echo "unexpected drrun warnings:"; echo "$out_and_err"; exit 1 ;;
    esac

    runHook postInstallCheck
  '';

  meta = {
    description = "Dynamic binary instrumentation engine";
    longDescription = ''
      DynamoRIO runs a target process under a JIT code cache, letting a client
      observe or rewrite every instruction. Ships drrun, the drcachesim
      cache/TLB simulator, drcov, and the client API.

      Clients build against $out/cmake. DynamoRIOConfig.cmake propagates
      -fno-stack-protector to them, so a client packaged for Nix needs the same
      hardeningDisable as this package.

      `drrun -attach <pid>` also needs kernel.yama.ptrace_scope=0, which a
      derivation cannot arrange. Launching (`drrun -- <app>`) is unaffected.
    '';
    homepage = "https://dynamorio.org/";
    changelog = "https://github.com/DynamoRIO/dynamorio/releases/tag/cronbuild-${finalAttrs.version}";
    license = with lib.licenses; [
      bsd2 # core
      lgpl21Only # ext/drwrap, ext/drutil
      lgpl3Only # ext/drsyms, via the bundled elfutils
      gpl2Only # tools/genhtml
      bsd3 # libelftc
    ];
    # Upstream documents aarch64 as a cross target only.
    platforms = [ "x86_64-linux" ];
    mainProgram = "drrun";
  };
})
